import {
  FaCouch,
  FaGlassCheers,
  FaSwimmer,
  FaGamepad,
  FaFilm,
  FaDumbbell,
  FaCoffee,
  FaChargingStation,
  FaTheaterMasks,
  FaChild,
  FaBriefcase,
  FaUtensils,
  FaCut,
  FaSpa,
  FaBed,
  FaFirstAid,
  FaShoppingBasket,
  FaShower,
  FaBook,
  FaBasketballBall,
  FaUsers,
  FaBirthdayCake,
  FaVolleyballBall,
  FaGopuram,
  FaFire,
  FaGolfBall,
} from "react-icons/fa";

export const AMENITIES = [
  { key: "welcomeLounge", label: "Welcome Lounge", icon: <FaCouch /> },
  { key: "banquetHall", label: "Banquet Hall", icon: <FaGlassCheers /> },
  { key: "badminton", label: "Badminton Court", icon: <FaSwimmer /> },
  { key: "swimmingPool", label: "Swimming Pool", icon: <FaSwimmer /> },
  { key: "indoorGames", label: "Indoor Games", icon: <FaGamepad /> },
  { key: "theatre", label: "Theatre", icon: <FaFilm /> },
  { key: "gym", label: "Gym", icon: <FaDumbbell /> },
  { key: "cafe", label: "Café", icon: <FaCoffee /> },
  { key: "evCharging", label: "EV Charging", icon: <FaChargingStation /> },
  { key: "spa", label: "Spa", icon: <FaSpa /> },
  { key: "library", label: "Library", icon: <FaBook /> },
  { key: "basketball", label: "Basketball Court", icon: <FaBasketballBall /> },
  { key: "community", label: "Community Space", icon: <FaUsers /> },
  { key: "partyLawn", label: "Party Lawn", icon: <FaBirthdayCake /> },
  { key: "volleyball", label: "Volleyball Court", icon: <FaVolleyballBall /> },
  { key: "temple", label: "Temple", icon: <FaGopuram /> },
  { key: "barbeque", label: "Barbeque", icon: <FaFire /> },
  { key: "miniGolf", label: "Mini Golf Court", icon: <FaGolfBall /> },
];

